[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shumi-model"
version = "0.0.1"
requires-python = ">=3.9"

[tool.setuptools]
py-modules = ["device", "predict", "model", "train", "inference", "shumi_action"]
